### PR TITLE
Added EXTREMELY important updates

### LINKED ISSUE #3: Index.html needs more cowbell
It just really needs it.

### PR DESCRIPTION
**Pull request by Randy-Williams**
Don't know why this wasn't implemented to begin with. Shame...

### CODE REVIEW

**Review by aszigethy — APPROVED** [review]
didnt even check ¯\_(ツ)_/¯

**Comment by ryan-guzman** [comment]
we are good programmers

**Comment by ryan-guzman** [comment]
> didnt even check ¯_(ツ)_/¯

quote

**Comment by ryan-guzman** [comment]
this issue is fixed

**Comment by ryan-guzman** [comment]
whoops!

**Comment by ryan-guzman** [comment]
this cowbell looks great

**Pull request merged**
